modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="C0-1.0"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}" #mandatory
logoFile = "multiloader.png" #optional
authors="${mod_author}" #optional
description='''
This is a long form description of the mod. You can write whatever you want here
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
