modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="MPL-2"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}" #mandatory
authors="${mod_author}" #optional
description='''
Commands!
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
